//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEVE_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTORDER
    {
        public CUSTORDER()
        {
            this.ORDERITEMS = new HashSet<ORDERITEMS>();
        }
    
        public int CUSTORDERID { get; set; }
        public int CUSTID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual ICollection<ORDERITEMS> ORDERITEMS { get; set; }
    }
}
