//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEVE_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERS
    {
        public CUSTOMERS()
        {
            this.CUSTORDER = new HashSet<CUSTORDER>();
        }
    
        public int CUSTID { get; set; }
        public string LASTNAME { get; set; }
        public string PRENAME { get; set; }
        public string STREET { get; set; }
        public string POSTCODE { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<sbyte> BUSINESSPARTNER { get; set; }
    
        public virtual ICollection<CUSTORDER> CUSTORDER { get; set; }
    }
}
