//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEVE_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERITEMS
    {
        public int ITEMID { get; set; }
        public int CUSTORDERID { get; set; }
        public int ARTICLENUMBER { get; set; }
        public string COLORCODE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string COLORNAME { get; set; }
        public sbyte HASPRINT { get; set; }
        public Nullable<int> PRINTNUMBER { get; set; }
    
        public virtual CUSTORDER CUSTORDER { get; set; }
    }
}
