//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEVE_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VEVEEntities : DbContext
    {
        public VEVEEntities()
            : base("name=VEVEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public DbSet<CUSTORDER> CUSTORDER { get; set; }
        public DbSet<ORDERITEMS> ORDERITEMS { get; set; }
    }
}
